CREATE TABLE poker_user (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR,
    username VARCHAR,
    password VARCHAR,
    profile_url VARCHAR,
    bank_name VARCHAR,
    account_number VARCHAR,
    role VARCHAR,
    last_daily_bonus TIMESTAMP(6),
    avatar_border TEXT,
    avatar TEXT,
    cgp_score INTEGER DEFAULT 0,
    deleted_at TIMESTAMP(6),
    phone_number VARCHAR(20),
    verified BOOLEAN DEFAULT false,
    CONSTRAINT poker_user_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT unique_username UNIQUE (username)
);

CREATE TABLE poker_table (
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_name VARCHAR NOT NULL,
    max_players INTEGER NOT NULL,
    variant VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by INTEGER NOT NULL,
    small_blind INTEGER NOT NULL,
    big_blind INTEGER NOT NULL,
    min_buy_in INTEGER NOT NULL,
    max_buy_in INTEGER NOT NULL,
    secure_id VARCHAR(255),
    rake_percent NUMERIC(5,4) NOT NULL DEFAULT 0.05,
    card_bg_color VARCHAR(7),
    total_rake_collected INTEGER DEFAULT 0,
    CONSTRAINT poker_table_pkey PRIMARY KEY (table_id)
);

CREATE TABLE poker_user_balance (
    user_id INTEGER NOT NULL,
    balance INTEGER DEFAULT 0,
    locked_amount INTEGER DEFAULT 0,
    last_bonus_session_id VARCHAR(64),
    bonus_balance INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT poker_user_balance_pkey PRIMARY KEY (user_id),
    CONSTRAINT fk_balance_user FOREIGN KEY (user_id) REFERENCES poker_user(user_id)
);

CREATE TABLE poker_deposit (
    deposit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    admin_id INTEGER,
    type VARCHAR NOT NULL,
    amount INTEGER NOT NULL,
    details JSONB NOT NULL,
    create_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    denied_reason TEXT,
    approved_date TIMESTAMP WITH TIME ZONE,
    approved_by INTEGER,
    CONSTRAINT poker_deposit_pkey PRIMARY KEY (deposit_id),
    CONSTRAINT fk_deposit_user FOREIGN KEY (user_id) REFERENCES poker_user(user_id),
    CONSTRAINT fk_deposit_admin FOREIGN KEY (admin_id) REFERENCES poker_user(user_id)
);

CREATE TABLE poker_withdrawal (
    withdrawal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER,
    amount INTEGER,
    create_date TIMESTAMP WITH TIME ZONE,
    approved_by INTEGER,
    approve_date TIMESTAMP WITH TIME ZONE,
    details JSONB,
    status VARCHAR(20) DEFAULT 'PENDING',
    CONSTRAINT poker_withdrawal_pkey PRIMARY KEY (withdrawal_id)
);

CREATE TABLE poker_outcome (
    outcome_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER,
    amount INTEGER,
    is_accounted BOOLEAN NOT NULL DEFAULT false,
    create_date TIMESTAMP WITH TIME ZONE NOT NULL,
    account_date TIMESTAMP WITH TIME ZONE,
    type VARCHAR NOT NULL,
    CONSTRAINT poker_winning_pkey PRIMARY KEY (outcome_id)
);

CREATE TABLE poker_game_session (
    table_id INTEGER NOT NULL,
    details JSONB NOT NULL,
    create_date TIMESTAMP WITH TIME ZONE NOT NULL,
    session_id VARCHAR NOT NULL,
    CONSTRAINT poker_game_session_pkey PRIMARY KEY (session_id)
);

CREATE TABLE poker_hand_history (
    hand_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_id INTEGER,
    hand_number BIGINT,
    winner_user_id INTEGER,
    winning_hole_cards JSONB,
    winning_community_cards JSONB,
    winnings INTEGER,
    created_at TIMESTAMP(6) DEFAULT now(),
    winner_username VARCHAR(255),
    CONSTRAINT poker_hand_history_pkey PRIMARY KEY (hand_id),
    CONSTRAINT fk_hand_history_table FOREIGN KEY (table_id) REFERENCES poker_table(table_id)
);

CREATE TABLE poker_jackpot (
    jackpot_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount BIGINT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT now(),
    seed_amount NUMERIC(19,2) DEFAULT 1000.00,
    last_updated TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    current_amount NUMERIC(19,2) DEFAULT 0.00,
    CONSTRAINT poker_jackpot_pkey PRIMARY KEY (jackpot_id)
);

CREATE TABLE poker_chat_message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_id BIGINT,
    user_id INTEGER NOT NULL,
    username VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT now(),
    CONSTRAINT poker_chat_message_pkey PRIMARY KEY (message_id),
    CONSTRAINT fk_chat_table FOREIGN KEY (table_id) REFERENCES poker_table(table_id),
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES poker_user(user_id)
);

CREATE TABLE poker_data_block (
    name TEXT NOT NULL,
    value TEXT NOT NULL,
    CONSTRAINT poker_data_block_pkey PRIMARY KEY (name)
);
