CREATE TABLE poker_hand_settlement (
    settlement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_id INTEGER NOT NULL,
    hand_number BIGINT NOT NULL,
    rake_amount INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT poker_hand_settlement_pkey PRIMARY KEY (settlement_id)
);

CREATE TABLE poker_hand_player_result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_id INTEGER NOT NULL,
    hand_number BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    username VARCHAR(255),
    is_bot BOOLEAN NOT NULL DEFAULT false,
    net_result INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT poker_hand_player_result_pkey PRIMARY KEY (result_id),
    CONSTRAINT fk_player_result_table FOREIGN KEY (table_id) REFERENCES poker_table(table_id)
);

CREATE INDEX idx_hand_settlement_created_at ON poker_hand_settlement (created_at);
CREATE INDEX idx_hand_player_result_created_at ON poker_hand_player_result (created_at);
