-- Tournament System Tables

-- Main tournament table
CREATE TABLE poker_tournament (
    tournament_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_name VARCHAR NOT NULL,
    description TEXT,
    tournament_type VARCHAR NOT NULL DEFAULT 'FREEZEOUT', -- FREEZEOUT, REBUY, BOUNTY, SATELLITE
    game_variant VARCHAR NOT NULL DEFAULT 'TEXAS_HOLDEM',
    
    -- Schedule
    registration_start TIMESTAMP WITH TIME ZONE NOT NULL,
    registration_end TIMESTAMP WITH TIME ZONE NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    
    -- Status: PENDING, REGISTERING, RUNNING, PAUSED, COMPLETED, CANCELLED
    status VARCHAR NOT NULL DEFAULT 'PENDING',
    
    -- Prizes
    prize_pool INTEGER NOT NULL DEFAULT 0,
    guaranteed_prize_pool INTEGER DEFAULT 0,
    places_paid INTEGER NOT NULL DEFAULT 0,
    prize_distribution JSONB, -- { "1": 0.5, "2": 0.3, "3": 0.2 }
    
    -- Buy-in structure
    buy_in INTEGER NOT NULL DEFAULT 0,
    entry_fee INTEGER NOT NULL DEFAULT 0, -- House fee
    rebuy_amount INTEGER,
    rebuy_fee INTEGER,
    addon_amount INTEGER,
    addon_fee INTEGER,
    max_rebuys INTEGER DEFAULT 0,
    addon_allowed BOOLEAN DEFAULT false,
    
    -- Chips
    starting_chips BIGINT NOT NULL DEFAULT 0,
    rebuy_chips BIGINT,
    addon_chips BIGINT,
    
    -- Blinds
    blind_structure JSONB NOT NULL, -- Array of { level, smallBlind, bigBlind, ante, duration }
    current_blind_level INTEGER DEFAULT 0,
    next_blind_increase TIMESTAMP WITH TIME ZONE,
    
    -- Seating
    max_players INTEGER NOT NULL DEFAULT 0,
    min_players INTEGER NOT NULL DEFAULT 2,
    tables_count INTEGER DEFAULT 0,
    seats_per_table INTEGER DEFAULT 9,
    
    -- Registration
    late_registration_allowed BOOLEAN DEFAULT true,
    late_registration_end_level INTEGER,
    
    -- Metadata
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    cancelled_reason TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT poker_tournament_pkey PRIMARY KEY (tournament_id),
    CONSTRAINT fk_tournament_creator FOREIGN KEY (created_by) REFERENCES poker_user(user_id)
);

-- Tournament registration/entries
CREATE TABLE poker_tournament_entry (
    entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    
    -- Entry details
    entry_type VARCHAR NOT NULL DEFAULT 'BUYIN', -- BUYIN, REBUY, ADDON
    amount_paid INTEGER NOT NULL,
    chips_received BIGINT NOT NULL,
    seat_number INTEGER,
    table_id BIGINT,
    
    -- Status: REGISTERED, SEATED, ELIMINATED, REBOUGHT, ADDON, CANCELLED
    status VARCHAR NOT NULL DEFAULT 'REGISTERED',
    
    -- Timing
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    seated_at TIMESTAMP WITH TIME ZONE,
    eliminated_at TIMESTAMP WITH TIME ZONE,
    eliminated_level INTEGER,
    final_position INTEGER,
    prize_won INTEGER DEFAULT 0,
    
    -- Rebuy/Addon tracking
    rebuy_count INTEGER DEFAULT 0,
    addon_taken BOOLEAN DEFAULT false,
    
    CONSTRAINT poker_tournament_entry_pkey PRIMARY KEY (entry_id),
    CONSTRAINT fk_entry_tournament FOREIGN KEY (tournament_id) REFERENCES poker_tournament(tournament_id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_user FOREIGN KEY (user_id) REFERENCES poker_user(user_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_tournament UNIQUE (tournament_id, user_id)
);

-- Tournament blind schedule
CREATE TABLE poker_tournament_blind_level (
    blind_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT NOT NULL,
    level_number INTEGER NOT NULL,
    small_blind INTEGER NOT NULL,
    big_blind INTEGER NOT NULL,
    ante INTEGER DEFAULT 0,
    duration_minutes INTEGER NOT NULL,
    is_break BOOLEAN DEFAULT false,
    break_duration_minutes INTEGER DEFAULT 0,
    
    CONSTRAINT poker_tournament_blind_level_pkey PRIMARY KEY (blind_id),
    CONSTRAINT fk_blind_tournament FOREIGN KEY (tournament_id) REFERENCES poker_tournament(tournament_id) ON DELETE CASCADE,
    CONSTRAINT unique_tournament_level UNIQUE (tournament_id, level_number)
);

-- Tournament prizes/awards
CREATE TABLE poker_tournament_prize (
    prize_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT NOT NULL,
    position INTEGER NOT NULL, -- 1, 2, 3, etc.
    percentage NUMERIC(5,4), -- e.g., 0.5 for 50%
    fixed_amount INTEGER, -- Alternative to percentage
    description VARCHAR,
    
    CONSTRAINT poker_tournament_prize_pkey PRIMARY KEY (prize_id),
    CONSTRAINT fk_prize_tournament FOREIGN KEY (tournament_id) REFERENCES poker_tournament(tournament_id) ON DELETE CASCADE,
    CONSTRAINT unique_tournament_position UNIQUE (tournament_id, position)
);

-- Tournament payouts/transactions
CREATE TABLE poker_tournament_payout (
    payout_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT NOT NULL,
    entry_id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    payout_type VARCHAR NOT NULL, -- PRIZE, REBUY_REFUND, CANCELLATION_REFUND
    status VARCHAR NOT NULL DEFAULT 'PENDING', -- PENDING, COMPLETED, FAILED
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT poker_tournament_payout_pkey PRIMARY KEY (payout_id),
    CONSTRAINT fk_payout_tournament FOREIGN KEY (tournament_id) REFERENCES poker_tournament(tournament_id) ON DELETE CASCADE,
    CONSTRAINT fk_payout_entry FOREIGN KEY (entry_id) REFERENCES poker_tournament_entry(entry_id) ON DELETE CASCADE,
    CONSTRAINT fk_payout_user FOREIGN KEY (user_id) REFERENCES poker_user(user_id) ON DELETE CASCADE
);

-- Tournament tables (mapping tournament to game tables)
CREATE TABLE poker_tournament_table (
    tournament_table_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    table_number INTEGER NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'WAITING', -- WAITING, ACTIVE, BROKEN, COMPLETED
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT poker_tournament_table_pkey PRIMARY KEY (tournament_table_id),
    CONSTRAINT fk_tt_tournament FOREIGN KEY (tournament_id) REFERENCES poker_tournament(tournament_id) ON DELETE CASCADE,
    CONSTRAINT fk_tt_table FOREIGN KEY (table_id) REFERENCES poker_table(table_id) ON DELETE CASCADE,
    CONSTRAINT unique_tournament_table UNIQUE (tournament_id, table_number)
);

-- Indexes for performance
CREATE INDEX idx_tournament_status ON poker_tournament(status);
CREATE INDEX idx_tournament_start_time ON poker_tournament(start_time);
CREATE INDEX idx_tournament_registration ON poker_tournament(registration_start, registration_end);
CREATE INDEX idx_tournament_creator ON poker_tournament(created_by);

CREATE INDEX idx_entry_tournament ON poker_tournament_entry(tournament_id);
CREATE INDEX idx_entry_user ON poker_tournament_entry(user_id);
CREATE INDEX idx_entry_status ON poker_tournament_entry(status);
CREATE INDEX idx_entry_table ON poker_tournament_entry(table_id);

CREATE INDEX idx_blind_tournament ON poker_tournament_blind_level(tournament_id);
CREATE INDEX idx_prize_tournament ON poker_tournament_prize(tournament_id);
CREATE INDEX idx_payout_tournament ON poker_tournament_payout(tournament_id);
CREATE INDEX idx_payout_entry ON poker_tournament_payout(entry_id);
CREATE INDEX idx_payout_user ON poker_tournament_payout(user_id);
CREATE INDEX idx_payout_status ON poker_tournament_payout(status);

CREATE INDEX idx_tt_tournament ON poker_tournament_table(tournament_id);
CREATE INDEX idx_tt_table ON poker_tournament_table(table_id);
CREATE INDEX idx_tt_status ON poker_tournament_table(status);